webdav:
    port: 8080
    user: usenet
    password: usenet
api:
    prefix: /api
auth:
    login_required: true
database:
    path: /config/altmount.db
metadata:
    root_path: /config/metadata
    delete_source_nzb_on_removal: false
streaming:
    max_download_workers: 15
    max_cache_size_mb: 32
health:
    enabled: false
    library_dir: null
    cleanup_orphaned_files: false
    check_interval_seconds: 5
    max_connections_for_health_checks: 5
    max_concurrent_jobs: 1
    segment_sample_percentage: 5
    library_sync_interval_minutes: 0
    library_sync_concurrency: 0
rclone:
    path: /config
    password: ""
    salt: ""
    rc_enabled: false
    rc_url: ""
    rc_port: 5573
    rc_user: admin
    rc_pass: admin
    rc_options: {}
    mount_enabled: false
    vfs_name: altmount
    mount_options: {}
    log_level: INFO
    uid: 1000
    gid: 1000
    umask: "002"
    buffer_size: 32M
    attr_timeout: 1s
    transfers: 4
    cache_dir: /config/cache
    vfs_cache_mode: full
    vfs_cache_poll_interval: ""
    vfs_read_chunk_size: ""
    vfs_cache_max_size: 50G
    vfs_cache_max_age: 504h
    read_chunk_size: 32M
    read_chunk_size_limit: 2G
    vfs_read_ahead: 128M
    dir_cache_time: 10m
    vfs_cache_min_free_space: 1G
    vfs_disk_space_total: 1G
    vfs_read_chunk_streams: 4
    allow_other: true
    allow_non_empty: true
    read_only: false
    timeout: 10m
    syslog: true
    no_mod_time: false
    no_checksum: false
    async_read: false
    vfs_fast_fingerprint: false
    use_mmap: false
import:
    max_processor_workers: 2
    queue_processing_interval_seconds: 5
    allowed_file_extensions:
        - .mp4
        - .mkv
        - .avi
        - .mov
        - .wmv
        - .flv
        - .webm
        - .m4v
        - .mpg
        - .mpeg
        - .m2ts
        - .ts
        - .vob
        - .3gp
        - .3g2
        - .h264
        - .h265
        - .hevc
        - .ogv
        - .ogm
        - .strm
        - .iso
        - .img
        - .divx
        - .xvid
        - .rm
        - .rmvb
        - .asf
        - .asx
        - .wtv
        - .mk3d
        - .dvr-ms
    max_import_connections: 5
    import_cache_size_mb: 64
    segment_sample_percentage: 1
    import_strategy: NONE
    import_dir: null
    watch_dir: /config/watch
    watch_interval_seconds: 15
log:
    file: /config/altmount.log
    level: info
    max_size: 100
    max_age: 30
    max_backups: 10
    compress: true
sabnzbd:
    enabled: false
    complete_dir: /complete
    categories: []
    fallback_host: ""
    fallback_api_key: ""
arrs:
    enabled: false
    max_workers: 5
    radarr_instances: []
    sonarr_instances: []
fuse:
    mount_path: ""
    enabled: false
    allow_other: true
    debug: false
    attr_timeout_seconds: 1
    entry_timeout_seconds: 1
    max_download_workers: 15
    max_cache_size_mb: 128
    max_read_ahead_mb: 128
providers: []
mount_path: ""
profiler_enabled: false
